---
title: blogdown
author: ''
date: '2019-06-18'
slug: blogdown
categories: []
tags: []
output:
  html_document:
    keep_md: yes
---

There has been lots of talk about blogdown on #rstats Twitter recently and people have been talking up the Hugo "Academic theme". 

I want to give it a go to update my lab website, so thought it might be a good idea to pull together all the useful links I've seen recently into one place. 

#### Alison Hill

I used [Alison's blog post](https://alison.rbind.io/post/up-and-running-with-blogdown/) when I first set up this blog. It looks like she has updated the post recently, so it is probably still a good place to start. 

Since then Alison has also written a [book about blogdown](https://bookdown.org/yihui/blogdown/), run a RStudioConf19 [Advanced RMarkdown workshop](https://arm.rbind.io/), done [a talk at SDSS](http:/rstd.io/blogdown-sdss) and now works at RStudio. [Her website](https://alison.rbind.io/) is a lovely example of the Academic theme and contains links all her talks/workshops/publications. 

Most recently she has [challenged her RStudio summer interns](https://twitter.com/apreshill/status/1138626886618083328) to a [Summer of blogdown challenge](https://summer-of-blogdown.netlify.com/). 

#### Dan Quintana 

Dan did a [Twitter live thing in 2018](https://twitter.com/dsquintana/status/1070392412445401088) showing how you could put the basic structure of an Academic website together within an hour. 

He updated that recently in a [new Twitter live](https://twitter.com/dsquintana/status/1139846569623281664) and supplemented it with a [step by step blog post](https://www.dsquintana.blog/free-website-in-r-easy/).

