---
title: 'fomo on #useR2018'
author: Jen Richmond
date: '2018-07-16'
slug: fomo-on-user2018
categories: []
tags: []
output:
  html_document:
    keep_md: yes
---

I have been travelling for the last few weeks, first to a teaching conference at Duke called PsychOne, and then to the International Congress on Infant Studies (ICIS) in Philadelphia. There was a surprising amount of #rstats at ICIS which was awesome. Everyone is talking about reproducible science and preregistration and best practices that will improve our field. There is definitely another blog post needed to consolidate my notes from ICIS, but for now, I want to write about #useR2018 (a conference I didn't get to go to). 


I was really disappointed to hear that the biggest international R conference was scheduled to be in Australia while I was in the USA, and for the past week or so I have been experiencing serious fomo. I have been glued to twitter and feeling envious. BUT... because the R community is open and inclusive and amazing, all of the tutorials and keynotes have been recorded and uploaded to youtube. 

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">So stoked to find the <a href="https://twitter.com/hashtag/useR2018?src=hash&amp;ref_src=twsrc%5Etfw">#useR2018</a> Workshops &amp; Tutorials playlist on <a href="https://twitter.com/YouTube?ref_src=twsrc%5Etfw">@YouTube</a>.  Feeling a little less bad about missing <a href="https://twitter.com/useR2018_conf?ref_src=twsrc%5Etfw">@useR2018_conf</a> <a href="https://t.co/1w5aakvnah">https://t.co/1w5aakvnah</a></p>&mdash; Dr Jenny Richmond (@JenRichmondPhD) <a href="https://twitter.com/JenRichmondPhD/status/1018120759955292161?ref_src=twsrc%5Etfw">July 14, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

So I want to pull all the things I want to look at over the next few weeks into one place. 

First, all of the Workshops and Tutorials can be found on a [playlist here](https://www.youtube.com/playlist?list=PL4IzsxWztPdnyAKQQLxA4ucpaCLdsKvZw). 


#### Things that I have on my "must check this out" list...

##### Keynotes

1. Keynote by @RLadiesSydney co-founder [Steph de Silva re open communities](https://www.youtube.com/watch?v=27FxbDtCFoc&t=24s)

2. Keynote by @RLadiesSydney co-founder [Dani Navarro on R in Psych Science](https://www.youtube.com/watch?v=xFkEbYk0C0Q&t=3s)

3. Keynote by [Jenny Bryan about smelly code](https://github.com/jennybc/code-smells-and-feels#readme) (I'm not sure what that means, but I think I need to know about it)

4. Keynote by [Roger Peng about Teaching R to new users](https://www.youtube.com/watch?v=5033jBHFiHE) 

5. Keynote by [Thomas Lin Pedersen re `gganimate`](https://www.youtube.com/watch?v=21ZWDrTukEs) 

##### Other relevant stuff

###### Tidyverse stuff:

* workshop by Simon Jackson about wrangling [part 1](https://www.youtube.com/watch?v=E-Vvg8uzcVM) and [part 2](https://www.youtube.com/watch?v=DwWH1mTerOc) 
* talk by Earo Wang about [time series `tsibble` package](https://www.youtube.com/watch?v=v6yRmbulxUM) 

###### Data Visualisation stuff: 

* Keynote re [`gganimate`](https://www.youtube.com/watch?v=21ZWDrTukEs) by Thomas Lin Pedersen
* Talk by Carson Sievert re interactive visualisation with R & plotly [part 1](https://www.youtube.com/watch?v=VTA8HGwL2Os) and [part 2](https://www.youtube.com/watch?v=FGS3MZAPshY)

###### Analysis stuff:  

* Talk about the [`infer` package by Chester Ismay](https://www.youtube.com/watch?v=BCMjVc9ncFo)
* Talk by John Fox about the [`car` and `effects` package](https://www.youtube.com/watch?v=aIxQz2wH-vk)
* Talk by Sevvandi Kandanaarachchi about [normalising data and outlier detection](https://www.youtube.com/watch?v=KGIPh_DFb8U)

###### Data cleaning stuff: 

* Workshop by Johann Gagnon-Bartsch about dealing with unwanted variation [part 1](https://www.youtube.com/watch?v=Z9IjfmSRfVU) and [part 2](https://www.youtube.com/watch?v=HUcZQC3xWDo)
* Tutorial by Max Kuhn about data processing recipes [part 1](https://www.youtube.com/watch?v=JacpQdj1Vfc&t=164s) [part 2](https://www.youtube.com/watch?v=ss-pIcwOUFo)
* Another talk about from Max Kuhn about [preprocessing using recipes](https://www.youtube.com/watch?v=Gta4-ft8nBc)

###### Social media stuff: 

Follow me workshop by Maria Prokofieva [part 1](https://www.youtube.com/watch?v=ped2DVtGipY) and [part 2](https://www.youtube.com/watch?v=DvQEHhP6pVo)

###### Teaching stuff: 

* Talk by Francois Michonneau from Carpentries about [R-based curricula](https://www.youtube.com/watch?v=kcw4BeCjbDQ) 
* Keynote by Roger Peng about [Teaching R to new users](https://www.youtube.com/watch?v=5033jBHFiHE) 
* Talk by Mette Langaas about [teaching stats in Rmarkdown](https://www.youtube.com/watch?v=lr9JybM5lww&t=31s)

######  Other cool looking stuff: 

* Talk by Thomas Klebel about analysing journal articles with [`jstor`package](https://www.youtube.com/watch?v=kNRbT-ki9tU&t=45s)
* Talk by Adrian Barnett about using [`shiny` to create pub lists](https://www.youtube.com/watch?v=pebg0rAE-V0)
* Talk by John Blischak about [`workflowR` package](https://www.youtube.com/watch?v=GrqM2VqIQ20) for reproducible science 
* Talk about [`varameta` package](https://www.youtube.com/watch?v=_P6cY_ipzDI) by Charles Gray 
* Talk by Bill Venables from CSIRO about [adventures with R] (https://www.youtube.com/watch?v=NNCD5g-wI9U) using  psycholinguistics and fisheries examples

